scrape_configs:
  - job_name: "snmp"
    static_configs:
      - targets:
          - 172.22.0.97 # SNMP device.
          - 172.22.0.99
          - 172.22.0.100
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /snmp
    params:
      auth: [auth_name]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116 # The SNMP exporter's real hostname:port.

  # Global exporter-level metrics
  - job_name: "snmp_exporter"
    static_configs:
      - targets: ["snmp_exporter:9116"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
